# Start with Blue style
# Make a couple of changes noted below

always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
import_to_using = true

# GJL Usually almost all of a module is a submodule
indent_submodule = false

# GJL
pipe_to_function_call = false

remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = true
whitespace_in_kwargs = false
whitespace_ops_in_indices = true
yas_style_nesting = false
